## 1. Import Libraries

In [37]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

## 2. Load Dataset

In [38]:
df=pd.read_csv('../data/train.csv')

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 3. Drop Unnecesarry Columns

In [40]:
df=df.drop(columns=["PassengerId","Name","Ticket","Cabin"])

In [41]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [42]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

## 4. Train-Test Split

In [43]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=0)

In [44]:
X_train

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C
378       3    male  20.0      0      0   4.0125        C
491       3    male  21.0      0      0   7.2500        S
..      ...     ...   ...    ...    ...      ...      ...
835       1  female  39.0      1      1  83.1583        C
192       3  female  19.0      1      0   7.8542        S
629       3    male   NaN      0      0   7.7333        Q
559       3  female  36.0      1      0  17.4000        S
684       2    male  60.0      1      1  39.0000        S

[712 rows x 7 columns]

## 5. Automatic column type detection

In [45]:
num_cols = X_train.select_dtypes(include=['number']).columns
cat_cols = X_train.select_dtypes(include=['object']).columns

In [46]:
print("Numerical Columns:", num_cols)
print("Categorical Columns:", cat_cols)

Numerical Columns: Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')
Categorical Columns: Index(['Sex', 'Embarked'], dtype='object')

## 6. Create Numerical Pipeline

In [47]:
num_pipe=Pipeline([
    ('imputer',SimpleImputer(strategy='mean')),
    ('scaler',MinMaxScaler())
])

In [48]:
num_pipe.named_steps

{'imputer': SimpleImputer(), 'scaler': MinMaxScaler()}

## 7. Create Numerical Pipeline

In [49]:
cat_pipe=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])

## 8. Combine Pipelines using ColumnTransformer

In [50]:
preprocessor= ColumnTransformer(
    [
        ('num',num_pipe,num_cols),
        ('cat',cat_pipe,cat_cols)
    ]
)

In [51]:
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', MinMaxScaler())]),
                                 Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['Sex', 'Embarked'], dtype='object'))])

## 9. Fit and Transform Training Data

In [52]:
X_train_processed=preprocessor.fit_transform(X_train)

## 10. Convert back to DataFrame

In [53]:
preprocessor.get_feature_names_out()

array(['num__Pclass', 'num__Age', 'num__SibSp', 'num__Parch', 'num__Fare',
       'cat__Sex_female', 'cat__Sex_male', 'cat__Embarked_C',
       'cat__Embarked_Q', 'cat__Embarked_S'], dtype=object)

In [54]:
X_train_processed=pd.DataFrame(X_train_processed,columns=preprocessor.get_feature_names_out())

In [55]:
X_train_processed.head()

,num__Pclass,num__Age,num__SibSp,num__Parch,num__Fare,cat__Sex_female,cat__Sex_male,cat__Embarked_C,cat__Embarked_Q,cat__Embarked_S
0,1.0,0.366509,0.000,0.333333,0.029758,1.0,0.0,1.0,0.0,0.0
1,0.5,0.382327,0.000,0.000000,0.020495,0.0,1.0,0.0,0.0,1.0
2,0.5,0.382327,0.125,0.166667,0.072227,0.0,1.0,1.0,0.0,0.0
3,1.0,0.243666,0.000,0.000000,0.007832,0.0,1.0,1.0,0.0,0.0
4,1.0,0.256271,0.000,0.000000,0.014151,0.0,1.0,0.0,0.0,1.0

## 11. Transform Test Data

In [56]:
X_test_processed=preprocessor.transform(X_test)

## 12. Convert to DataFrame

In [57]:
X_test_processed=pd.DataFrame(X_test_processed,columns=preprocessor.get_feature_names_out())

## 13. Test on Kaggle Test dataset

In [58]:
test_df=pd.read_csv("../data/test.csv")

In [59]:
test_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

## 14. Dropping unnecessary columns

In [60]:
test_df=test_df.drop( columns=['PassengerId','Name','Ticket','Cabin'])

In [61]:
test_df.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

## 15. Transformation

In [62]:
test_processed=preprocessor.transform(test_df);

In [63]:
test_processed=pd.DataFrame(test_processed,columns=preprocessor.get_feature_names_out())

In [64]:
print(test_processed)

     num__Pclass  num__Age  num__SibSp  num__Parch  num__Fare  \
0            1.0  0.426446       0.000    0.000000   0.015282
1            1.0  0.584016       0.125    0.000000   0.013663
2            0.5  0.773100       0.000    0.000000   0.018909
3            1.0  0.331905       0.000    0.000000   0.016908
4            1.0  0.268877       0.125    0.166667   0.023984
..           ...       ...         ...         ...        ...
413          1.0  0.366509       0.000    0.000000   0.015713
414          0.0  0.483172       0.000    0.000000   0.212559
415          1.0  0.476869       0.000    0.000000   0.014151
416          1.0  0.366509       0.000    0.000000   0.015713
417          1.0  0.366509       0.125    0.166667   0.043640

     cat__Sex_female  cat__Sex_male  cat__Embarked_C  cat__Embarked_Q  \
0                0.0            1.0              0.0              1.0
1                1.0            0.0              0.0              0.0
2                0.0            1.0              0.0              1.0
3                0.0            1.0              0.0              0.0
4                1.0            0.0              0.0              0.0
..               ...            ...              ...              ...
413              0.0            1.0              0.0              0.0
414              1.0            0.0              1.0              0.0
415              0.0            1.0              0.0              0.0
416              0.0            1.0              0.0              0.0
417              0.0            1.0              1.0              0.0

     cat__Embarked_S
0                0.0
1                1.0
2                0.0
3                1.0
4                1.0
..               ...
413              1.0
414              0.0
415              1.0
416              1.0
417              0.0

[418 rows x 10 columns]

In [65]:
test_processed.head()

,num__Pclass,num__Age,num__SibSp,num__Parch,num__Fare,cat__Sex_female,cat__Sex_male,cat__Embarked_C,cat__Embarked_Q,cat__Embarked_S
0,1.0,0.426446,0.000,0.000000,0.015282,0.0,1.0,0.0,1.0,0.0
1,1.0,0.584016,0.125,0.000000,0.013663,1.0,0.0,0.0,0.0,1.0
2,0.5,0.773100,0.000,0.000000,0.018909,0.0,1.0,0.0,1.0,0.0
3,1.0,0.331905,0.000,0.000000,0.016908,0.0,1.0,0.0,0.0,1.0
4,1.0,0.268877,0.125,0.166667,0.023984,1.0,0.0,0.0,0.0,1.0

In [66]:
import joblib

In [67]:
joblib.dump(preprocessor,"../models/preprocessor.pkl")

['../models/preprocessor.pkl']

In [68]:
loaded_preprocessor=joblib.load("../models/preprocessor.pkl")

In [69]:
loaded_preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', MinMaxScaler())]),
                                 Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['Sex', 'Embarked'], dtype='object'))])

In [70]:
loaded_test=loaded_preprocessor.transform(test_df)

In [71]:
print(loaded_test.shape)

(418, 10)